import { useState, useCallback } from 'react'
import Head from 'next/head'
import type { NextPage } from 'next'
import { useAccount } from 'wagmi'
import { AnimatePresence } from 'framer-motion'

import { InterfaceContext } from '../shared/contexts'
import { useIsMounted } from '../shared/hooks'

import { Stack } from '@mui/joy'

import Header from '../components/Header'
import Controls from '../components/Controls'
import SettingsPanel from '../components/SettingsPanel'

const Home: NextPage = () => {
    let { isConnected } = useAccount()
    let isMounted = useIsMounted()
    let [isSettingsPanelOpen, setIsSettingsPanelOpen] = useState(false)

    let openSettingsPanel = useCallback(() => {
        setIsSettingsPanelOpen(true)
    }, [])

    let closeSettingsPanel = useCallback(() => {
        setIsSettingsPanelOpen(false)
    }, [])

    return (
        <InterfaceContext.Provider
            value={{
                openSettingsPanel,
                closeSettingsPanel
            }}
        >
            <Stack>
                <Head>
                    <title>NftMarketplace</title>
                    <meta
                        name='description'
                        content='Generated by create next app'
                    />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <Header />
                {isConnected && isMounted && <Controls sx={{ padding: 2 }} />}
            </Stack>
            <AnimatePresence>
                {isSettingsPanelOpen && (
                    <SettingsPanel
                        onClose={(): void => setIsSettingsPanelOpen(false)}
                    />
                )}
            </AnimatePresence>
        </InterfaceContext.Provider>
    )
}

export default Home
